version: '3'
services:
  database-mysql:
    container_name: database-mysql
    image: mysql/mysql-server:8.0

    environment:
      MYSQL_ROOT_PASSWORD: 'simple'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'simple'
      TZ: Asia/Seoul

    volumes:
      - ./mysql-init.d:/docker-entrypoint-initdb.d

    ports:
      - '3306:3306'

    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
  application:
    container_name: simple-order-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - database-mysql